# Generated by Django 5.2.6 on 2025-10-17 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_rename_like_likepost_likecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together={('comment', 'user')},
        ),
    ]
