# Generated by Django 5.2.6 on 2025-10-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
